#!/usr/bin/env sh

# SPDX-FileCopyrightText: (c) 2024 ale5000
# SPDX-License-Identifier: GPL-3.0-or-later
# shellcheck enable=all

# shellcheck disable=SC3045 # Ignore: In POSIX sh, export -n is undefined
export -n PS1 || true
