version = 1

[[annotations]]
path = [
  ".public-keys/*.gpg",
  "fastlane/metadata/android/en-US/*.txt",
  "gradle/wrapper/gradle-wrapper.properties",
  "allowed_signers",
  "Gemfile.lock"
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
