version = 1

[[annotations]]
path = [
  ".public-keys/*.gpg",
  "fastlane/metadata/android/en-US/*.txt",
  "gradle/wrapper/gradle-wrapper.properties",
  "allowed_signers",
  "Gemfile.lock"
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
  ".vscode/*.json"
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileComment = [
  "https://code.visualstudio.com/docs/editor/tasks",
  "https://code.visualstudio.com/docs/editor/variables-reference"
]
