# SPDX-FileCopyrightText: NONE
# SPDX-License-Identifier: CC0-1.0

sonar.projectKey=micro5k_microg-unofficial-installer
sonar.organization=micro5k

# This is the name displayed in the SonarQube UI
sonar.projectName=microG unofficial installer

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Explicitly set the Python version for more precise analysis
sonar.python.version=3.14

# Ignore NOSONAR_BEGIN / NOSONAR_END blocks
sonar.issue.ignore.block=e1
sonar.issue.ignore.block.e1.beginBlockRegexp=NOSONAR_BEGIN
sonar.issue.ignore.block.e1.endBlockRegexp=NOSONAR_END

# List of exceptions
sonar.issue.ignore.multicriteria=e1

# e1 => Ignore shelldre:S7688 (Use "[[" instead of "[" for conditional tests)
sonar.issue.ignore.multicriteria.e1.ruleKey=shelldre:S7688
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.sh

# Disable coverage
sonar.coverage.exclusions=**/*
