#!/usr/bin/env sh

# SPDX-FileCopyrightText: (c) 2022 ale5000
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileType: SOURCE

if test -n "$1"; then
  echo "Dummy mount: $*"
  return 0 2>&- || exit 0
fi

echo "\
rootfs on / type rootfs (rw,seclabel)
tmpfs on /dev type tmpfs (rw,seclabel,nosuid,relatime,mode=755)
devpts on /dev/pts type devpts (rw,seclabel,relatime,mode=600)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,seclabel,relatime)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
tmpfs on ${TMPDIR:?} type tmpfs (rw,seclabel,relatime)
${TMPDIR:?} on /tmp type tmpfs (rw,seclabel,relatime)
/dev/block/bootdevice/by-name/userdata on ${ANDROID_DATA:?} type ext4 (rw,seclabel,relatime,data=ordered)
${ANDROID_DATA:?} on /data type ext4 (rw,seclabel,relatime,data=ordered)
/dev/block/bootdevice/by-name/cache on /cache type ext4 (rw,seclabel,relatime,data=ordered)
/dev/block/bootdevice/by-name/sdcard0 on /sdcard0 type vfat (rw,relatime,errors=remount-ro)
/dev/block/bootdevice/by-name/sdcard1 on /sdcard1 type vfat (rw,relatime,errors=remount-ro)
/dev/block/bootdevice/by-name/system on ${ANDROID_ROOT:?} type ext4 (rw,seclabel,relatime,data=ordered)
${ANDROID_ROOT:?} on /system type ext4 (rw,seclabel,relatime,data=ordered)\
/system/system_ext on /system_ext type ext4 (rw,seclabel,relatime,data=ordered)\
/system/product on /product type ext4 (rw,seclabel,relatime,data=ordered)\
/system/vendor on /vendor type ext4 (rw,seclabel,relatime,data=ordered)\
"
