#!/usr/bin/env sh

# SPDX-FileCopyrightText: (c) 2016-2019, 2021 ale5000
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileType: SOURCE

if test -n "$1"; then
  echo "unmounted: $*"
  return 0 2>&- || exit 0
fi

echo "umount: bad usage"
echo "Try 'umount --help' for more information."
return 1 2>&- || exit 1
