#!/usr/bin/env sh

# SPDX-FileCopyrightText: (c) 2022 ale5000
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileType: SOURCE

if test -n "$1"; then
  echo "Dummy umount: $*"
  return 0 2>&- || exit 0
fi

echo "umount: bad usage"
return 1 2>&- || exit 1
