---
# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

name: "🐞 Bug report"
description: Report a bug to help improve this software.
labels: ["bug", "needs triage"]
assignees:
  - ale5000-git
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: "e.g. v1.0.29-beta"
    validations:
      required: true
  - type: input
    id: android-version
    attributes:
      label: Android version
      description: What version of Android do you use?
      placeholder: "e.g. 10"
    validations:
      required: true
  - type: input
    id: custom-rom
    attributes:
      label: Custom ROM
      description: What ROM are you using?
      placeholder: "e.g. LineageOS 17.1"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: log
