---
# SPDX-FileCopyrightText: NONE
# SPDX-License-Identifier: CC0-1.0

name: "Android permissions generation"
permissions: {}
on:
  workflow_dispatch:
  schedule:
    # Runs at 02:00, every 6 days
    - cron: "0 2 */6 * *"

jobs:
  generate-permissions:
    name: "Generate permission XMLs"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: "${{ github.event_name != 'schedule' }}"
    permissions:
      contents: read # Needed to checkout the repository (only required for private repositories)

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v7
        with:
          path: "./repo"
          lfs: true
          sparse-checkout: |
            **/*.apk
          sparse-checkout-cone-mode: false
      - name: "Checkout scripts"
        uses: actions/checkout@v7
        timeout-minutes: 5
        with:
          path: "./scripts-repo"
          repository: "micro5k/microg-unofficial-installer"
          persist-credentials: false
          lfs: false
          sparse-checkout: |
            tools/dl-perm-list.sh
            tools/generate-perm-xml.sh
          sparse-checkout-cone-mode: false
      - name: "Use perms cache"
        id: perms-cache
        uses: actions/cache@v6
        timeout-minutes: 5
        with:
          key: "perms-${{ hashFiles('scripts-repo/tools/dl-perm-list.sh') }}"
          path: "cache/perms"
          enableCrossOsArchive: true
      - name: "Execute scripts"
        shell: bash
        timeout-minutes: 10
        env:
          CACHE_HIT: "${{ steps.perms-cache.outputs.cache-hit }}"
        run: |
          # Executing scripts...
          export OUTPUT_DIR='./scripts-repo/output'
          export TOOLS_DATA_DIR='./cache'
          if test "${CACHE_HIT?}" != 'true' || test ! -f './cache/perms/.completed'; then
            './scripts-repo/tools/dl-perm-list.sh' || exit "${?}"
          fi
          set -- './repo/zip-content' || exit "${?}"
          test ! -d './cache/build' || set -- "${@}" './cache/build' || exit "${?}"
          find "${@}" -name '*.apk' | './scripts-repo/tools/generate-perm-xml.sh' --use-placeholders - || exit "${?}"
      - name: "Store artifacts"
        uses: actions/upload-artifact@v7
        timeout-minutes: 10
        with:
          name: "XML permissions"
          path: "${{ github.workspace }}/scripts-repo/output/*.xml"
          retention-days: 10
          overwrite: false
          if-no-files-found: "error"

  keep-cache-alive:
    name: "Keep cache alive"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "${{ github.event_name == 'schedule' }}"
    permissions:
      contents: read # Needed to checkout the repository (only required for private repositories)
      actions: write # Needed to keep alive the workflow

    steps:
      - name: "Checkout file"
        uses: actions/checkout@v7
        timeout-minutes: 5
        with:
          path: "./scripts-repo"
          repository: "micro5k/microg-unofficial-installer"
          persist-credentials: false
          lfs: false
          sparse-checkout: |
            tools/dl-perm-list.sh
          sparse-checkout-cone-mode: false
      - name: "Ping perms cache" # Cache expiration: 7 days
        uses: actions/cache/restore@v6
        timeout-minutes: 5
        with:
          key: "perms-${{ hashFiles('scripts-repo/tools/dl-perm-list.sh') }}"
          path: "cache/perms"
          enableCrossOsArchive: true
          lookup-only: true
      - name: "Keep this workflow alive"
        uses: actions/github-script@v9
        timeout-minutes: 5
        with:
          retries: 3
          script: |
            /* jshint esversion: 11 */
            const workflow_id = process.env.GITHUB_WORKFLOW_REF.split('@', 1).at(0).split('/').pop(); // context.workflow_ref
            await github.rest.actions.enableWorkflow({ ...context.repo, workflow_id })
              .then(() => console.log('Success.'))
              .catch(err => { throw new Error('enableWorkflow failed with error ' + err.status + ' (' + err.message + ')'); });
