---
# SPDX-FileCopyrightText: NONE
# SPDX-License-Identifier: CC0-1.0

name: "Android permissions generation"
permissions: {}
on:
  workflow_dispatch:
  schedule:
    # Runs at 02:00, every 6 days
    - cron: "0 2 */6 * *"

jobs:
  generate-permissions:
    name: "Generate Android permission XMLs"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: "${{ github.event_name != 'schedule' }}"
    permissions:
      contents: read # Needed to checkout the repository (only required for private repositories)

    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v7
        with:
          lfs: true
          sparse-checkout: |
            tools/dl-perm-list.sh
            tools/generate-perm-xml.sh
            **/*.apk
          sparse-checkout-cone-mode: false
      - name: "Use perms cache"
        id: perms-cache
        uses: actions/cache@v6
        timeout-minutes: 5
        with:
          key: "perms-${{ hashFiles('tools/dl-perm-list.sh') }}"
          path: "cache/tools/perms"
          enableCrossOsArchive: true
      - name: "Execute scripts"
        shell: bash
        timeout-minutes: 10
        env:
          CACHE_HIT: "${{ steps.perms-cache.outputs.cache-hit }}"
        run: |
          # Executing scripts...
          export OUTPUT_DIR='./output'
          export TOOLS_DATA_DIR='./cache/tools'
          if test "${CACHE_HIT?}" != 'true' || test ! -f './cache/tools/perms/.completed'; then
            './tools/dl-perm-list.sh' || exit "${?}"
          fi
          set -- './zip-content' || exit "${?}"
          test ! -d './cache/build' || set -- "${@}" './cache/build' || exit "${?}"
          find "${@}" -name '*.apk' | './tools/generate-perm-xml.sh' --use-placeholders - || exit "${?}"
      - name: "Store artifacts"
        uses: actions/upload-artifact@v7
        timeout-minutes: 10
        with:
          name: "XML permissions"
          path: "${{ github.workspace }}/output/*.xml"
          retention-days: 10
          overwrite: false
          if-no-files-found: "error"

  keep-cache-alive:
    name: "Keep cache alive"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: "${{ github.event_name == 'schedule' }}"
    permissions:
      contents: read # Needed to checkout the repository (only required for private repositories)
      actions: write # Needed to keep alive the workflow

    steps:
      - name: "Checkout file"
        uses: actions/checkout@v7
        with:
          lfs: false
          sparse-checkout: |
            tools/dl-perm-list.sh
          sparse-checkout-cone-mode: false
      - name: "Ping perms cache" # Cache expiration: 7 days
        uses: actions/cache/restore@v6
        timeout-minutes: 5
        with:
          key: "perms-${{ hashFiles('tools/dl-perm-list.sh') }}"
          path: "cache/tools/perms"
          enableCrossOsArchive: true
          lookup-only: true
      - name: "Keep workflow alive"
        uses: actions/github-script@v9
        timeout-minutes: 5
        env:
          WORKFLOW_REF: "${{ github.workflow_ref }}"
        with:
          retries: 3
          script: |
            /* jshint esversion: 11 */
            const workflow_filename = process.env.WORKFLOW_REF.split('@', 1).at(0).split('/').slice(2).join('/');
            const response = await github.rest.actions.enableWorkflow({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow_filename
            }).catch(response => response);
            if(response && response.status === 204) {
              console.log('Workflow enabled.');
            } else {
              let errorMsg = 'enableWorkflow failed';
              if(response && response.status && response.message) errorMsg += ' with error ' + response.status + ' (' + response.message + ')';
              throw new Error(errorMsg);
            }
